### ISSUE TITLE
Input - Upload Component

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/thriving-park#133]
# Adds Input[type="upload"] Component

## Subtasks

- [ ] - Update `InputType` type def
- [ ] - Create `Upload` directory in `src/stories/Inputs`
- [ ] - Add file types (.stories, .tsx, .test.tsx, .style.ts)

**Comment by wijohnst** [comment]
The story should have 4 states:

- `Default`
- `Uploading` 
- `Success`
- `Failed`
