### ISSUE TITLE
Feature - `<TextArea />` Component

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/thriving-park#68]
<img width="550" alt="Screen Shot 2022-01-08 at 4 32 47 PM" src="https://user-images.githubusercontent.com/12022922/148660818-44ef0895-0053-4bb5-809b-68ceb1bb9a8b.png">

## Tasks
- [ ] Update `InputType` interface - `Input.tsx` 
- [ ] Add `TextArea` story files
- [ ] Add `TextArea` markup
- [ ] Unit tests

## States

1. Default
2. Active
3. Placeholder
4. Character count
