### ISSUE TITLE
Update `<Input />` component with `<TextInput />`, `<Select />`, and `<TextArea />` props

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/thriving-park#69]
## Tasks

- [x] - Add `options` for `<Select />` 
- [x] - Add `rows`, `placeholder`, and `maxCharacterLength` for `<TextArea />` 
- [x] - Add `placeholder` for `<TextInput />`
